group:
  - files:
      - source: _extensions/seedcase-theme/
        dest: _extensions/seedcase-project/seedcase-theme/
        deleteOrphaned: true
    repos: |
      seedcase-project/community
      seedcase-project/design
      seedcase-project/team
      seedcase-project/seedcase-website
      seedcase-project/decisions
      seedcase-project/seedcase-sprout

