---
title: "Welcome"
description: "This is an example page to show how the styling works."
---

## Introduction

This is the test landing page! With a [link](https://duckduckgo.com/)!
And an emoji :grin:

[An about link button](nonexisting-link){.btn .about-link}
[Another one next to it](nonexisting-link){.btn .about-link}


And [longer reference to another header](index.qmd#another) in the same
document.

Random text: The shoes had been there for as long as anyone could
remember. In fact, it was difficult for anyone to come up with a date
they had first appeared. It had seemed they'd always been there and yet
they seemed so out of place. Why nobody had removed them was a question
that had been asked time and again, but while they all thought it,
nobody had ever found the energy to actually do it. So, the shoes
remained on the steps, out of place in one sense, but perfectly normal
in another.

Here's a table:

| Name | Age |
|------|-----|
| John | 23  |
| Jane | 24  |

A list:

1.  first
2.  second
3.  third

![This is a
caption](_extensions/seedcase-theme/logos/seedcase/icon.svg){width="200"}

A callout block:

::: callout-tip
### Header within callout block

Some text.
:::

## Another header with `code`

### H3 with `code`

#### H4 with `code`

##### H5 with `code`

###### H6 with `code`

Here's some `inline code` in a sentence.

A code block:

``` python
def hello_world():
    print("Hello, world!")
```

## Simple mermaid diagram

::: column-page
```{mermaid}
%%| fig-cap: "Simple mermaid diagram"
flowchart TB
    user(["User<br>[person]"])
    subgraph sprout [Python package]
        package["Data package functions<br>[Python]<br><br>Create, manage, and check a data package and its 'properties' (metadata)."]
    end
    output[("Filesystem<br><br>Stored data and metadata on a local or server filesystem.")]

    user --> sprout:::system
    package --> metadata
    sprout --> output:::external

    classDef system fill:none
    classDef external fill:lightgrey
```
:::
