@startuml test-state-diagram
!theme seedcase from ../_extensions/seedcase-theme

title Test state diagram

state "Group" as group {
  state "<&plus> One element" as element_1
  element_1 : - bullet point 

  state "<&magnifying-glass> Another element" as element_2
  element_2 : - bullet point 
}

@enduml
