@startuml test-c4-diagram
!theme seedcase from ../
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Test C4 diagram

Boundary(bou2, "Boundary 2") {
  Person(person, "Data contributor", "Adds data and resolves problems with data before upload")
  Person_Ext(per_ext, "External person", "Optional description")
}

System_Boundary(sys_bou, "System boundary") {
  System(sys, "System", "Optional description")
  System_Ext(sys_ext, "External system", "Optional description")
}

Container_Boundary(con_bou, "Container boundary") {
  Container(con, "Container label", "Technology", "Optional description")
  ContainerDb(con_db, "Container database", "Technology", "Optional description")
  Container_Ext(con_ext, "External container", "Technology", "Optional description")
  ContainerDb_Ext(con_db_ext, "External container", "Technology", "Optional description")
}

Boundary(bou1, "Boundary 1") {
  Component(com, "Component", "Technology","Optional description")
  Component_Ext(com_ext, "External component", "Technology", "Optional description")
}

sys_bou -[hidden]-> con_bou
sys_bou -[hidden]-> bou1
bou1 -[hidden]-> bou2

Rel_R(person, per_ext, "Relation")
BiRel_R(sys, sys_ext, "Bidirectional\nrelation")

SHOW_FLOATING_LEGEND()

@enduml

